version: "3"

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  db:
